services:

  redis:
    image: redis:latest

  reverse-proxy:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "4000:4000"

  web:
    build: .
    ports:
    - "5000"


networks:
  default:
    driver: bridge
